version: '3.8'
services:
    mongodb:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - mongodb_data:/data/db
    script:
        build:
            context: .
            dockerfile: Dockerfile_script
            args:
                DATA_PATH: ${DATA_PATH}
        env_file:
            - .env
        depends_on:
            - mongodb
    app:
        build:
            context: .
            dockerfile: Dockerfile_app
        # TODO: Spring Boot can't read the env variable, it needs to be set in application.properties
        # TODO: to the value of the env variable, too much time was wasted trying to get it to work
        env_file:
            - .env
        ports:
            - 8080:8080
        depends_on:
            - mongodb
volumes:
    mongodb_data:
