version: '3.8'
services:
    mongodb:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - mongodb_data:/data/db
    import:
        build:
            context: .
            dockerfile: Dockerfile_import
        env_file:
            - .env
        volumes:
            - import_data:/data
        depends_on:
            - mongodb
    app:
        build:
            context: .
            dockerfile: Dockerfile_app
            args:
                MONGODB_URI: ${MONGODB_URI}
        env_file:
            - .env
        ports:
            - 8080:8080
        depends_on:
            - mongodb
volumes:
    mongodb_data:
    import_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${DATA_PATH}
