version: '3.8'
services:
    mongodb:
        build:
            context: .
            dockerfile: Dockerfile_mongodb
        ports:
            - 27017:27017
        volumes:
            - mongodb_data:/data/db
            - ./db:/scripts
    app:
        build:
            context: .
            dockerfile: Dockerfile_app
        ports:
            - 8080:8080
        depends_on:
            - mongodb
volumes:
    mongodb_data:
