version: '3.8'
services:
    mongodb:
        build:
            context: .
            dockerfile: Dockerfile_mongodb
        ports:
            - 27017:27017
        volumes:
            - mongodb_data:/data/db
            - ./db:/scripts
    app:
        build:
            context: .
            dockerfile: Dockerfile_app
        # TODO: Spring Boot can't read the env variable, it needs to be set in application.properties
        # TODO: all attempts to fix this here or in Dockfile failed :(
        environment:
            - MONGODB_URI=mongodb://mongodb:27017/dnd
        ports:
            - 8080:8080
        depends_on:
            - mongodb
volumes:
    mongodb_data:
